version: '3.8'
services:
#  web:
#    container_name: backend
#    build: ./
#    volumes:
#      - code:/backend
#      - node_modules:/node_modules
#    links:
#      - redis
#      - mongo
##    command: yarn start
#    env_file:
#      - ./.env
#    ports:
#      - "8000:8000"
#    networks:
#      - mean-stack-net
  angular:
    build:
      context: ../mepchat                   # Change if needed to the frontend dir
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: angular
    networks:
      - mean-stack-net
    volumes:
      - ../mepchat/src:/usr/app/src         # Change if needed to the frontend dir
      - ../mepchat/public:/usr/app/public   # Change if needed to the frontend dir
#    depends_on:
#      - web
    stdin_open: true
    tty: true
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    networks:
      - mean-stack-net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - mean-stack-net
volumes:
  mongo:
  redis:
  code:
  node_modules:

networks:
  mean-stack-net:
    driver: bridge
#    external: true
